### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by deborahferguson** [cameronspowell/bio-dlf#28]
Attempting to send feedback crashed. Trying again immediately also crashed, but within a few minutes it was working again. Have not been able to recreate issue since.
![screenshot_20170419-154546](https://cloud.githubusercontent.com/assets/6587139/26160493/66f1b138-3aef-11e7-8366-228f778ff951.png)

**Comment by cameron-powell** [comment]
Seems to be a mail service issue blocking logins for security purposes.  Attempted fix in mail service settings (outside the code).  Seems to be working now.  Will leave this open for now to make sure that this solution fixed the issue.

[attempted](https://stackoverflow.com/questions/20337040/gmail-smtp-debug-error-please-log-in-via-your-web-browser)

**Comment by cameron-powell** [comment]
Issue has been fixed.
