### ISSUE TITLE
Text Updates

### ISSUE THREAD

**Issue by deborahferguson** [cameronspowell/bio-dlf#32]
Contact Information:
Change "Howey N209" to "Boggs 1-38"

Education section:
Add in masters degree
M.S. in Physics, Georgia Institute of Technology (2017)
(Think about best way to say this since I'm still at GA tech)

Research section:
Change "Accepted for publication in ApJ" to "Published in ApJ"

Teaching section:
Move current to previous (will know new current soon)

**Comment by cameron-powell** [comment]
Updated to current
